name: build

on: [push]

env:
  MSPEC_TEST_DLL: .\MongoMembership.Tests\bin\Debug\MongoMembership.Tests.dll

jobs:
  build:

    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Restore packages
        run: MSBuild.exe -t:restore -p:RestorePackagesConfig=true
      - name: Build
        run: MSBuild.exe
      - name: Unit test with MSpec
        run: |
          $ConsoleRunnerPackage = Get-ChildItem .\packages -Filter Machine.Specifications.Runner.Console.*
          . $ConsoleRunnerPackage\tools\mspec-clr4.exe $Env:MSPEC_TEST_DLL
